### ISSUE TITLE
Correct read-only admin label

### ISSUE THREAD

**Issue by PxlBuzzard** [codeRIT/brickhack.io#227] opened 2015-04-18 13:37 UTC
I don't know if this is a bug, but I think it is.

**Comment by sman591** [comment] 2015-04-18 13:40
It's by design, just was never re-labeled for what the role actually entails. Limits abilities, but not entirely.

**Comment by sman591** [comment] 2015-12-28 22:02
Closed in #276

**Closed by sman591** 2015-12-28 22:02 UTC
Labels: maintenance
